import Head from "next/head";
import * as React from "react";

export interface LayoutProps {
  children?: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <body className="text-white">
      <Head>
        <title>Strongest MTG</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-10 bg-white container" />
      <main className="flex-col h-[calc(100vh-40px)] flex items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

      {children}
      </main>
    </body>
  );
}

export default Layout;
